app:
  firebase-configuration-file: firebase.json
  notifications:
    defaults:
      topic: "common"
      title: "Common topic - Hello"
      message: "Sending test message 😊"
      token: "ss22t03wz208eg:APA2idkkow223FE_0v5yHxqCLTyxAQafj6nWaqi4QzwZTW004q1PUux63UsFN"
      payloadMessageId: "123"
      payloadData: "Hello. This is payload content."
